image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master

.unit-test:
  image: python:3.9
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install cmake
    - apt-get update
    - apt-get install -y libgl1-mesa-glx
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt 
  script:
    - mkdir data
    - python3 manage.py makemigrations user task bank advertise
    - python3 manage.py migrate
    - sh ./test.sh

unit-test-other-branches:
  extends: .unit-test
  except:
    - dev
    - master
  

unit-test-main-branches:
  extends: .unit-test
  only:
    - dev
    - master
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master